In [66]:
import torch
import torch.nn as nn
import numpy
from sklearn.svm import SVC
import sys

In [78]:
b = 10
c = 1
TS = 1000

In [79]:
batch_size = b
train_size = 1000
length = 1000
nb_random_samples = 10
# For each batch element, we pick nb_random_samples possible random
# time series in the training set (choice of batches from where the
# negative examples will be sampled)
samples = numpy.random.choice(
    train_size, size=(nb_random_samples, batch_size)
)
samples = torch.LongTensor(samples)
print(samples.shape)

# Choice of length of positive and negative samples
length_pos_neg = numpy.random.randint(1, high=length + 1)
print(length_pos_neg)

# We choose for each batch example a random interval in the time
# series, which is the 'anchor'
random_length = numpy.random.randint(
    length_pos_neg, high=length + 1
)  # Length of anchors
print(random_length)

beginning_batches = numpy.random.randint(
    0, high=length - random_length + 1, size=batch_size
)  # Start of anchors

print("begining batches is {}".format(beginning_batches))
# The positive samples are chosen at random in the chosen anchors
beginning_samples_pos = numpy.random.randint(
    0, high=random_length - length_pos_neg + 1, size=batch_size
)  # Start of positive samples in the anchors

print("beginning _sample_pos {}".format(beginning_samples_pos))

# Start of positive samples in the batch examples
beginning_positive = beginning_batches + beginning_samples_pos
# End of positive samples in the batch examples
end_positive = beginning_positive + length_pos_neg

print(beginning_positive)
print(end_positive)
# We randomly choose nb_random_samples potential negative samples for
# each batch example
beginning_samples_neg = numpy.random.randint(
    0, high=length - length_pos_neg + 1,
    size=(nb_random_samples, batch_size)
)

torch.Size([10, 10])
832
847
begining batches is [133  82  90  27 109  17  43 119 150  52]
beginning _sample_pos [10 14 10  4  7 14  8 12 14  9]
[143  96 100  31 116  31  51 131 164  61]
[975 928 932 863 948 863 883 963 996 893]


In [80]:
batch = torch.Tensor(10, 1, 1000)

In [83]:
a = [batch[j: j + 1, :,beginning_batches[j]: beginning_batches[j] + random_length] for j in range(10)] 

In [86]:
a =torch.cat(a)

In [87]:
a.shape

torch.Size([10, 1, 847])

In [92]:
a = np.asarray([1, 2, 3, 4, 5])

In [93]:
b = np.asarray([1, 2, 3, 4, 5])

In [94]:
a+b

array([ 2,  4,  6,  8, 10])

In [95]:
a = [torch.Tensor(1, 1, 87) for i in range(10)]

In [96]:
aa = torch.cat(a)

In [97]:
aa.shape

torch.Size([10, 1, 87])